### ISSUE TITLE
.nss compilation fails on first run after making a change (Windows)

### ISSUE THREAD

**Issue by Riari** [jakkn/nwn-devbase#17] opened 2018-07-11 09:39 UTC
Hi,

I'm using the Docker image in a batch file like so:

```bat
@echo off
start /WAIT /B "" "docker" run --rm -it -v "%cd%:/home/devbase/build" jakkn/nwn-devbase
```

For some reason, after making changes to scripts, building fails on the first run and succeeds on the second:

```
F:\Projects\nwn-module (master -> origin)
λ nwn-build
[INFO] Converting from yml to gff (this may take a while)...
[INFO] Compiling nss
Error: No matching files for input wildcard path *.nss.

[ERROR] Something went wrong during nss compilation. Check the compiler output.
[ERROR] Aborting.

F:\Projects\nwn-module (master -> origin)
λ nwn-build
[INFO] Converting from yml to gff (this may take a while)...
[INFO] No change in nss sources detected. Skipping compilation.
[INFO] Building /home/devbase/build/server/modules/Sandbox.mod
[INFO] Done.
Total time: 0.3360373 seconds.
```

It's not a major problem since building happens so quickly (at least for now - I don't know what it's like with large modules). Just found it a bit odd.

Thanks for all of your work on this project btw!

Edit: I realised it seems not to compile scripts at all, no matter what I do. I always get the above output after changing a script - first `Error: No matching files for input wildcard path *.nss.`, then `No change in nss sources detected. Skipping compilation.`, even though the corresponding script under `.nwnproject/cache/gff` has an older modified timestamp on it.

**Comment by Riari** [comment] 2018-07-12 09:53
Here's full output from `nwn-build compile -v`, with debug output enabled on the compiler:

```
nwn-build compile -v
[DEBUG] Current environment:
  FLAT_LAYOUT: false
  START_TIME: 2018-07-12 09:51:00 +0000
  ARGV: ["compile"]
  EXECUTION_DIR: /usr/local/src/nwn-devbase
  WORKING_DIR: /home/devbase/build
  NWNPROJECT: /home/devbase/build/.nwnproject
  PROJECT_ROOT: /home/devbase/build
  PROJECT_USER_CONFIG:
  PROJECT_DEFAULT_CONFIG: /home/devbase/build/.nwnproject/config.rb.in
  GLOBAL_USER_CONFIG:
  GLOBAL_DEFAULT_CONFIG: /usr/local/src/nwn-devbase/config.rb.in
  HOME_DIR: /home/devbase/build/server
  INSTALL_DIR: /nwn/data
  MODULE_DIR: /home/devbase/build/server/modules
  MODULE_FILENAME: Sandbox
  MODULE_FILE_EXT: .mod
  MODULE_FILE: /home/devbase/build/server/modules/Sandbox.mod
  CACHE_DIR: /home/devbase/build/.nwnproject/cache
  TMP_CACHE_DIR: /home/devbase/build/.nwnproject/cache/tmp
  GFF_CACHE_DIR: /home/devbase/build/.nwnproject/cache/gff
  SRC_DIR: /home/devbase/build/src
  NUMBER_OF_SOURCES: 15
  NSS_DIR: /home/devbase/build/src/nss
  NSS_BATCHOUTDIR: /home/devbase/build/.nwnproject/cache/gff
  NSS_COMPILER: nwnsc
  COMPILER_ARGS: ["-oD", "-n", "/nwn/data", "-y", "-b", "/home/devbase/build/.nwnproject/cache/gff"]
  ERF_UTIL: nwn_erf
  GFF_UTIL: nwn-gff
  RESMAN_DIR: /home/devbase/build/resman
  EXTRACT_RAKE: /usr/local/src/nwn-devbase/extract.rake
  PACK_RAKE: /usr/local/src/nwn-devbase/pack.rake
  SYMLINK_RAKE: /usr/local/src/nwn-devbase/symlink.rake
  SCRIPTS_DIR: /usr/local/src/nwn-devbase/scripts
[INFO] Compiling nss
[DEBUG] Changed to /home/devbase/build/src/nss
[DEBUG] nwnsc -oD -n /nwn/data -y -b /home/devbase/build/.nwnproject/cache/gff *.nss
Loading base game resources...

2018-07-12 09:51:00,898 DEBUG [default] [user@2c186bb9458f] [std::string GetNwnHomePath(int, bool)] [/tmp/nwnsc/nwnsc/nwnsc.cpp:536]  HomePath ~/Documents/Neverwinter Nights/
Home Path - ~/Documents/Neverwinter Nights/

Error: No matching files for input wildcard path *.nss.

Total Execution time = 0.0450 seconds

[ERROR] Something went wrong during nss compilation. Check the compiler output.
[ERROR] Aborting.
```

**Comment by jakkn** [comment] 2018-07-12 11:23
Hi there, thank you for opening an issue.

```
2018-07-12 09:51:00,898 DEBUG [default] [user@2c186bb9458f] [std::string GetNwnHomePath(int, bool)] [/tmp/nwnsc/nwnsc/nwnsc.cpp:536]  HomePath ~/Documents/Neverwinter Nights/
Home Path - ~/Documents/Neverwinter Nights/
```

This shouldn't happen. It's possibly related to the recent update that Beamdog rolled out yesterday. Are you using the most recent image version? I will look more into it after I'm done at work in a few hours.

**Comment by Riari** [comment] 2018-07-12 11:31
Hey,

A friend is using the same setup (we're both using a fork of this repo) and gets the same output, but compiling works for him. So far, I don't see any difference between our setups since we're both using Docker as well.

As for the game and image versions, I had these issues before the game update was rolled out, but I made a point of deleting my local copy of the nwn-devbase image and pulling the latest version again. It seems to make no difference.

The cause seems like it must be something specific to my setup, but I'm not sure what to check. As I understand it, all of the dependencies exist in the Docker image. I am working on a drive other than the one where I have the game installed, but that seems irrelevant.

**Comment by jakkn** [comment] 2018-07-12 17:54
I am unable to reproduce so I agree that this appears to be specific to your setup. The batch command stands out to me as a potential culprit, particularly `%cd%`. I was unable to test this on my machine, so verify that the paths are correct.

I assume you're running docker natively since you're able to do this from windows batch, but in case you are somehow using docker-toolbox then remember that file sharing between your windows host and linux vm will only work from the home directory on your C:/ drive. However since debugging prints `NUMBER_OF_SOURCES: 15` it's apparent that some files are found, indicating that the mount is working.

What you could do is start a container shell and poke around. I usually run
`docker run --rm -it -v "$(pwd):/home/devbase/build" --entrypoint /bin/bash jakkn/nwn-devbase`
See if you find the files under src/nss/ that you're expecting to compile, and if you can touch files in .nwnproject/cache/gff/. You can also run `nwn-build compile` inside the container to compile your nss.

By the way - 15 sources is a very small number of files. Make sure there are nss targets to actually compile.

**Comment by Riari** [comment] 2018-07-12 18:17
Thanks for taking a look!

Sharing on drives other than C: does work on Docker for Windows, it just has to be explicitly enabled per drive. I have all of my repos on F: and volumes in other projects work just fine. We're also using a freshly created module, which probably explains the low number of files (e.g. we only have one script currently).

I tried your suggestion and everything appears to be present, but compiling still fails:

```
λ docker run --rm -it -v "F:/Projects/nwn-module:/home/devbase/build" --entrypoint /bin/bash jakkn/nwn-devbase
devbase@9fd2570920f5:~/build$ ls -a
.  ..  .git  .gitignore  .nwnproject  docker  docker-compose.yml  nwn-build.bat  readme.md  server  src
devbase@9fd2570920f5:~/build$ ls .nwnproject/cache/gff/
Repute.fac  area001.are  area001.gic  area001.git  creaturepalcus.itp  doorpalcus.itp  encounterpalcus.itp  itempalcus.itp  main.nss  module.ifo  placeablepalcus.itp  soundpalcus.itp  storepalcus.itp  triggerpalcus.itp  waypointpalcus.itpdevbase@9fd2570920f5:~/build$ ls src/nss/
main.nss
devbase@9fd2570920f5:~/build$ nwn-build compile
[INFO] Compiling nss
Loading base game resources...

2018-07-12 18:11:39,291 DEBUG [default] [user@9fd2570920f5] [std::string GetNwnHomePath(int, bool)] [/tmp/nwnsc/nwnsc/nwnsc.cpp:536]  HomePath ~/Documents/Neverwinter Nights/
Home Path - ~/Documents/Neverwinter Nights/
Error: No matching files for input wildcard path *.nss.

Total Execution time = 0.0530 seconds

[ERROR] Something went wrong during nss compilation. Check the compiler output.
[ERROR] Aborting.
```

I did wonder if an env var set by Cmder (what I normally use) might be causing some weirdness, so I tried the same thing from a plain Command Prompt and had the same result.

Another thing to note, not sure if it's relevant: if I delete `src` and run `nwn-build extract`, it works as expected and outputs everything, including the single `main.nss` we have in the module.

**Comment by jakkn** [comment] 2018-07-12 19:25
Yes it's definitely the compiler that's the issue. From what I can tell it fails to locate the base game resources, looking in what appears to be a windows path. This strikes me as odd, seeing that the process should be executing in a linux environment. Have you by any chance configured nwnsc to look under ~/Documents/Neverwinter Nights specifically? I notice you're passing `-oD` as a compiler argument. What does `-D` do? I can't see that flag in the `nwnsc --help` menu.

**Comment by Riari** [comment] 2018-07-12 20:27
I'm using all of the default values in `config.rb.in` except for MODULE_NAME and COMPILER_ARGS. The `-D` flag sets the log level to Debug and that's what outputs the line about the home path.

I agree it's very odd, although my friend can successfully compile in the same project, also on Windows 10, and still gets that line too. Example of his output:

```
nwn-build compile
[INFO] Compiling nss
Loading base game resources...

2018-07-12 09:50:40,143 DEBUG [default] [user@46daf3e06006] [std::string GetNwnHomePath(int, bool)] [/tmp/nwnsc/nwnsc/nwnsc.cpp:536]  HomePath ~/Documents/Neverwinter Nights/
Home Path - ~/Documents/Neverwinter Nights/

Compiling: main.nss
2018-07-12 09:50:40,193 DEBUG [default] [user@46daf3e06006] [virtual unsigned char* NscCompiler::LoadResource(const char*, NwnResType, UINT32*, bool*)] [/tmp/nwnsc/_NscLib/NscCompiler.cpp:1274] Checking include paths
2018-07-12 09:50:40,194 DEBUG [default] [user@46daf3e06006] [virtual unsigned char* NscCompiler::LoadResource(const char*, NwnResType, UINT32*, bool*)] [/tmp/nwnsc/_NscLib/NscCompiler.cpp:1336] Checking resource paths
Total Execution time = 0.0810 seconds
```

**Comment by jakkn** [comment] 2018-07-12 20:58
Ah debug flag, of course. I reproduced the same output now and it works.

Have you tried specifying main.nss compile target directly? `nwn-build compile main.nss`
You can also try running nwnsc directly in the container, instead of going via the nwn-build script. It's on path, so something like `cd src/nss/ && nwnsc -oD -n /nwn/data -b /home/devbase/build/.nwnproject/cache/gff main.nss` should work inside the container.

**Comment by Riari** [comment] 2018-07-12 21:14
Interesting - `nwn-build compile main.nss` works. It works outside of the container too (via the batch script). At least that means I can compile specific scripts, and it narrows the problem down - something to do with the way it searches for files?

I'm on the Edge channel for Docker for Windows, so maybe there's some obscure bug causing this. Nothing obvious in recently opened issues though.

**Comment by jakkn** [comment] 2018-07-13 15:55
Well that's at least something. Did you try `nwn-build compile *.nss` too?

**Comment by Riari** [comment] 2018-07-14 10:07
Yeah, tried that and got the same `Error: No matching files for input wildcard path *.nss.`

**Comment by jakkn** [comment] 2018-07-14 11:55
Well it could be a nwnsc bug, or a bug in how nwn-build passes the argument to nwnsc, but that's only speculation. Regardless, it's very hard for me to pinpoint what's wrong when I cannot reproduce.

I'm happy to answer any questions you may have and offer suggestions, but I will close the issue for now since it appears to be related to your environment and not the project.

**Closed as completed by jakkn** 2018-07-14 11:55 UTC

**Comment by Riari** [comment] 2018-07-14 13:26
That's fair, thanks for your time :)

If I figure it out I'll post here in case someone else does have the same issue.
