### ISSUE TITLE
Path issues

### ISSUE THREAD

**Issue by LordOfMyatar** [jakkn/nwn-devbase#31] opened 2019-11-19 21:54 UTC
Trying to run this command:
PS D:\Projects\LOM\lom> .\nwn-build.rb extract
[ERROR] Cannot find nwn_erf (needed for packing and extracting). Is it on your PATH?
[ERROR] Aborting.

I cannot find nwn_erf anywhere on my harddrive.  I can find nwn-erf in the ruby folder.  Am I missing something?

**Comment by squattingmonk** [comment] 2019-11-19 23:41
`nwn_erf` is from [neverwinter.nim](https:github.com/niv/neverwinter.nim) rather than nwn-lib. You can install that, but I think you can also set `ERF_UTIL` to `nwn-erf` in your config.rb.in.

**Comment by jakkn** [comment] 2019-11-21 16:39
Correct, `nwn_erf` is from the nim tools that offer a performance benefit compared to the ruby tools, with the downside of needing both. I had planned to move on to nim only, but yaml support dragged on. You can configure devbase to use `nwn-erf` if you want.

If ruby tools is too slow you can configure to use nim tools only, at the cost of json instead of yaml. Shout out if you need a hand and I can provide an example.

I'll close the issue for now since it's caused by environment configuration, but feel free to continue the conversation if you have further questions.

**Closed as completed by jakkn** 2019-11-21 16:39 UTC
